-- src/shared/Config/MonsterConfig.lua
-- All dungeon monsters and bosses. Stat values are per-level multipliers:
--   stat_at_level = math.floor(level * multiplier)
-- SilverReward / ExpReward: per-level multipliers (math.floor(level * N)).
-- GoldReward: { Chance, Multiplier, MinQty } for common/rare (qty = math.max(MinQty, math.floor(level*Multiplier)));
--             { Chance, MinQty, MaxQty } for bosses (fixed random range).
-- DropTable: guaranteed item drops only — no silver, no gold (handled above).
-- PhaseThresholds / PhaseStatMultipliers: IsBoss=true only; multipliers are deltas applied at transition.
-- ModelId: key into Assets.Models.Monsters.

return {

	-- ==========================================================================
	-- FOREST CAVE  (dungeon_forest) — entry Lv 21, step 8, boss Lv 77
	-- ==========================================================================

	goblin = {
		Name      = "Goblin",
		Element   = nil,
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = true,
		Dungeon   = "dungeon_forest",
		BaseStats = { HP = 15, ATK = 3, DEF = 1, SPD = 2 },
		ImmuneTo  = {},
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "basic_attack", "shiv", "group_tactics", "pickpocket" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "goblin_dagger", Chance = 0.08, MinQty = 1, MaxQty = 1 },
			{ ItemId = "iron_trap",    Chance = 0.04, MinQty = 1, MaxQty = 1 },
			{ ItemId = "basic_trap",   Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "goblin_coin",  Chance = 0.03, MinQty = 1, MaxQty = 3 },
		},
		SilverReward = 5,
		ExpReward    = 8,
		ModelId      = "goblin",
	},

	slime = {
		Name      = "Slime",
		Element   = "water",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = true,
		Dungeon   = "dungeon_forest",
		BaseStats = { HP = 22, ATK = 2, DEF = 2, SPD = 1 },
		ImmuneTo  = { "Poison", "Bleed" },
		ElementalVulnerability = { fire = 1.25 },
		AIBehavior  = "defensive",
		AbilityPool = { "slime_spit", "split_defense", "absorb", "ooze_coat" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "slime_essence",  Chance = 0.10, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_small", Chance = 0.06, MinQty = 1, MaxQty = 1 },
			{ ItemId = "basic_trap",     Chance = 0.04, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 8,
		ModelId      = "slime",
	},

	bat = {
		Name      = "Bat",
		Element   = "dark",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_forest",
		BaseStats = { HP = 8, ATK = 4, DEF = 0.5, SPD = 5 },
		ImmuneTo  = {},
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "bite", "screech", "wing_slash", "ultrasound_pulse", "echolocation" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "bat_wing",   Chance = 0.10, MinQty = 1, MaxQty = 1 },
			{ ItemId = "shadow_dust", Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "basic_trap", Chance = 0.04, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 8,
		ModelId      = "bat",
	},

	hobgoblin = {
		Name      = "Hobgoblin",
		Element   = nil,
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_forest",
		BaseStats = { HP = 20, ATK = 5, DEF = 2, SPD = 2.5 },
		ImmuneTo  = { "Shock", "Blind" },
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "axe_strike", "war_axe", "commander_shout", "battle_hardened" },
		GoldReward  = { Chance = 0.04, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "hobgoblin_shield", Chance = 0.06, MinQty = 1, MaxQty = 1 },
			{ ItemId = "goblin_dagger",   Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "iron_trap",       Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "gold_trap",       Chance = 0.01, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 15,
		ModelId      = "hobgoblin",
	},

	boss_goblin_warchief = {
		Name      = "Goblin Warchief",
		Element   = nil,
		IsBoss    = true,
		PhaseCount = 2,
		Capturable = false,
		Dungeon   = "dungeon_forest",
		BaseStats = { HP = 50, ATK = 4, DEF = 1.5, SPD = 2 },
		ImmuneTo  = { "Bind" },
		ElementalVulnerability = {},
		PhaseThresholds     = { [2] = 0.50 },
		PhaseStatMultipliers = {
			[1] = {},
			[2] = { ATK = 0.25 },  -- Goblin King's Rage: +25% ATK permanently
		},
		AIBehavior  = "aggressive",
		AbilityPool = {
			"warbrand_strike",
			"warbrand_slash",
			"shield_bash",
			"battle_cry",
			"goblin_kings_rage",
			"crown_throw",
		},
		GoldReward = { Chance = 1.00, MinQty = 10, MaxQty = 20 },
		DropTable  = {
			{ ItemId = "evolution_shard",       Chance = 0.60, MinQty = 1, MaxQty = 1 },
			{ ItemId = "rare_collectible",      Chance = 0.40, MinQty = 1, MaxQty = 1 },
			{ ItemId = "evolution_crystal",     Chance = 0.20, MinQty = 1, MaxQty = 1 },
			{ ItemId = "goblin_war_crown",      Chance = 0.15, MinQty = 1, MaxQty = 1 },
			{ ItemId = "legend_trap",           Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large",       Chance = 0.10, MinQty = 1, MaxQty = 1 },
			{ ItemId = "stamina_potion",        Chance = 0.10, MinQty = 2, MaxQty = 2 },
		},
		SilverReward = 50,
		ExpReward    = 100,
		ModelId      = "goblin_warchief",
	},

	-- ==========================================================================
	-- MOUNTAIN RUINS  (dungeon_mountain) — entry Lv 101, step 24, boss Lv 269
	-- ==========================================================================

	skeleton = {
		Name      = "Skeleton",
		Element   = nil,
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_mountain",
		BaseStats = { HP = 10, ATK = 5, DEF = 0.5, SPD = 2.5 },
		ImmuneTo  = { "Poison", "Bleed" },
		ElementalVulnerability = { fire = 1.50, light = 1.50 },
		AIBehavior  = "aggressive",
		AbilityPool = { "bone_strike", "bone_throw", "shatter", "brittle_form" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "bone_shard",      Chance = 0.08, MinQty = 1, MaxQty = 2 },
			{ ItemId = "lich_bone_shard", Chance = 0.02, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_small", Chance = 0.04, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 12,
		ModelId      = "skeleton",
	},

	ghost = {
		Name      = "Ghost",
		Element   = "dark",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_mountain",
		BaseStats = { HP = 10, ATK = 3.5, DEF = 0.5, SPD = 3 },
		ImmuneTo  = { "Poison", "Bleed" },
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "phase_touch", "haunting_wail", "chill_touch", "incorporeal" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "ghost_ectoplasm", Chance = 0.08, MinQty = 1, MaxQty = 1 },
			{ ItemId = "spectral_cloth",  Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_small", Chance = 0.04, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 12,
		ModelId      = "ghost",
	},

	vampire = {
		Name      = "Vampire",
		Element   = "dark",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_mountain",
		BaseStats = { HP = 18, ATK = 5, DEF = 1.5, SPD = 3 },
		ImmuneTo  = { "Poison", "Bleed" },
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "fang_strike", "blood_drain", "mesmerize", "night_fury", "bat_form" },
		GoldReward  = { Chance = 0.04, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "vampire_fang",    Chance = 0.06, MinQty = 1, MaxQty = 1 },
			{ ItemId = "blood_vial",      Chance = 0.08, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large", Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "gold_trap",       Chance = 0.01, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 18,
		ModelId      = "vampire",
	},

	boss_lich_king = {
		Name      = "Lich King",
		Element   = "dark",
		IsBoss    = true,
		PhaseCount = 2,
		Capturable = false,
		Dungeon   = "dungeon_mountain",
		BaseStats = { HP = 55, ATK = 4, DEF = 2, SPD = 1.5 },
		ImmuneTo  = { "Bind", "Poison", "Bleed" },
		ElementalVulnerability = {},
		PhaseThresholds     = { [2] = 0.50 },
		PhaseStatMultipliers = {
			[1] = {},
			[2] = { ATK = 0.20, DEF = 0.20 },  -- Lich's Defiance: +20% ATK & DEF permanently
		},
		AIBehavior  = "aggressive",
		AbilityPool = {
			"staff_strike",
			"frost_bolt",
			"soul_drain",
			"necrotic_curse",
			"lichs_defiance",
			"bone_army",
			"eternal_frost",
		},
		GoldReward = { Chance = 1.00, MinQty = 25, MaxQty = 50 },
		DropTable  = {
			{ ItemId = "evolution_shard",   Chance = 0.60, MinQty = 1, MaxQty = 1 },
			{ ItemId = "rare_collectible",  Chance = 0.40, MinQty = 1, MaxQty = 1 },
			{ ItemId = "evolution_crystal", Chance = 0.20, MinQty = 1, MaxQty = 1 },
			{ ItemId = "lich_bone_shard",   Chance = 0.15, MinQty = 1, MaxQty = 1 },
			{ ItemId = "legend_trap",       Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large",   Chance = 0.10, MinQty = 1, MaxQty = 1 },
			{ ItemId = "stamina_potion",    Chance = 0.10, MinQty = 2, MaxQty = 2 },
		},
		SilverReward = 50,
		ExpReward    = 100,
		ModelId      = "lich_king",
	},

	-- ==========================================================================
	-- DARK FOREST  (dungeon_darkforest) — entry Lv 101, step 24, boss Lv 269
	-- ==========================================================================

	elf_archer = {
		Name      = "Elf Archer",
		Element   = "nature",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_darkforest",
		BaseStats = { HP = 12, ATK = 4, DEF = 1, SPD = 3 },
		ImmuneTo  = {},
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "arrow_shot", "piercing_arrow", "natures_arrow", "evasive_roll" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "elven_arrow",    Chance = 0.08, MinQty = 1, MaxQty = 3 },
			{ ItemId = "elven_cloth",    Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "iron_trap",      Chance = 0.03, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_small", Chance = 0.04, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 12,
		ModelId      = "elf_archer",
	},

	hostile_fairy = {
		Name      = "Hostile Fairy",
		Element   = "nature",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_darkforest",
		BaseStats = { HP = 9, ATK = 4.5, DEF = 0.5, SPD = 4 },
		ImmuneTo  = {},
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "fairy_dust", "sparkle_blast", "curse_hex", "fairy_circle" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "fairy_dust",     Chance = 0.10, MinQty = 1, MaxQty = 1 },
			{ ItemId = "elven_leaf",     Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_small", Chance = 0.04, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 12,
		ModelId      = "hostile_fairy",
	},

	treant = {
		Name      = "Treant",
		Element   = "nature",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_darkforest",
		BaseStats = { HP = 22, ATK = 4, DEF = 2, SPD = 1 },
		ImmuneTo  = {},
		ElementalVulnerability = { fire = 1.50 },
		AIBehavior  = "defensive",
		AbilityPool = { "branch_sweep", "root_snare", "thorn_burst", "bark_shield", "overgrowth" },
		GoldReward  = { Chance = 0.04, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "ancient_bark",     Chance = 0.06, MinQty = 1, MaxQty = 1 },
			{ ItemId = "forest_sap",       Chance = 0.08, MinQty = 1, MaxQty = 1 },
			{ ItemId = "treant_heartwood", Chance = 0.02, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_small",  Chance = 0.05, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 18,
		ModelId      = "treant",
	},

	boss_elder_treant = {
		Name      = "Elder Treant",
		Element   = "nature",
		IsBoss    = true,
		PhaseCount = 2,
		Capturable = false,
		Dungeon   = "dungeon_darkforest",
		BaseStats = { HP = 60, ATK = 3.5, DEF = 2.5, SPD = 1 },
		ImmuneTo  = { "Bind" },
		ElementalVulnerability = { fire = 1.50 },
		PhaseThresholds     = { [2] = 0.50 },
		PhaseStatMultipliers = {
			[1] = {},
			[2] = {},  -- Heartwood Pulse (one-time heal) + Root Entanglement (behavioral) — no stat delta
		},
		AIBehavior  = "defensive",
		AbilityPool = {
			"branch_slam",
			"ancient_smash",
			"vine_wrap",
			"natures_wrath",
			"bark_armor",
			"heartwood_pulse",
			"root_entanglement",
		},
		GoldReward = { Chance = 1.00, MinQty = 60, MaxQty = 120 },
		DropTable  = {
			{ ItemId = "evolution_shard",   Chance = 0.60, MinQty = 1, MaxQty = 1 },
			{ ItemId = "rare_collectible",  Chance = 0.40, MinQty = 1, MaxQty = 1 },
			{ ItemId = "evolution_crystal", Chance = 0.20, MinQty = 1, MaxQty = 1 },
			{ ItemId = "treant_heartwood",  Chance = 0.15, MinQty = 1, MaxQty = 1 },
			{ ItemId = "legend_trap",       Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large",   Chance = 0.10, MinQty = 1, MaxQty = 1 },
			{ ItemId = "stamina_potion",    Chance = 0.10, MinQty = 2, MaxQty = 2 },
		},
		SilverReward = 50,
		ExpReward    = 100,
		ModelId      = "elder_treant",
	},

	-- ==========================================================================
	-- VOLCANO PIT  (dungeon_volcano) — entry Lv 301, step 48, boss Lv 637
	-- ==========================================================================

	orc = {
		Name      = "Orc",
		Element   = nil,
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_volcano",
		BaseStats = { HP = 20, ATK = 3.5, DEF = 2, SPD = 1.5 },
		ImmuneTo  = {},
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "club_smash", "warcry", "crushing_blow", "thick_hide" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "orc_fang",           Chance = 0.08, MinQty = 1, MaxQty = 1 },
			{ ItemId = "iron_club_fragment", Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "stamina_potion",     Chance = 0.04, MinQty = 1, MaxQty = 1 },
			{ ItemId = "iron_trap",          Chance = 0.02, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 15,
		ModelId      = "orc",
	},

	troll = {
		Name      = "Troll",
		Element   = nil,
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_volcano",
		BaseStats = { HP = 25, ATK = 3, DEF = 2, SPD = 1 },
		ImmuneTo  = {},
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "club_bash", "smash_down", "rock_throw", "troll_regeneration" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "troll_hide",     Chance = 0.08, MinQty = 1, MaxQty = 1 },
			{ ItemId = "crude_club",     Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_small", Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "stamina_potion", Chance = 0.02, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 15,
		ModelId      = "troll",
	},

	ogre = {
		Name      = "Ogre",
		Element   = "fire",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_volcano",
		BaseStats = { HP = 30, ATK = 5, DEF = 2.5, SPD = 1 },
		ImmuneTo  = { "ArmorBreak" },
		ElementalVulnerability = { ice = 1.25 },
		AIBehavior  = "aggressive",
		AbilityPool = { "boulder_fist", "mountain_smash", "volcanic_stomp", "roar_of_rage", "titan_hide" },
		GoldReward  = { Chance = 0.04, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "ogre_tusk",             Chance = 0.06, MinQty = 1, MaxQty = 1 },
			{ ItemId = "iron_boulder_fragment", Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large",       Chance = 0.04, MinQty = 1, MaxQty = 1 },
			{ ItemId = "stamina_potion",        Chance = 0.03, MinQty = 1, MaxQty = 1 },
			{ ItemId = "gold_trap",             Chance = 0.01, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 25,
		ModelId      = "ogre",
	},

	boss_orc_overlord = {
		Name      = "Orc Overlord",
		Element   = "fire",
		IsBoss    = true,
		PhaseCount = 3,
		Capturable = false,
		Dungeon   = "dungeon_volcano",
		BaseStats = { HP = 55, ATK = 5, DEF = 2, SPD = 2 },
		ImmuneTo  = { "Bind" },
		ElementalVulnerability = {},
		PhaseThresholds     = { [2] = 0.60, [3] = 0.30 },
		PhaseStatMultipliers = {
			[1] = {},
			[2] = { ATK = 0.25 },  -- Warlord's Rage: +25% ATK permanently
			[3] = { SPD = 0.25 },  -- Feral Instinct: +25% SPD permanently (ATK bonus from phase 2 already active)
		},
		AIBehavior  = "aggressive",
		AbilityPool = {
			"warbrand_strike",
			"warbrand_cleave",
			"volcanic_roar",
			"warlords_rage",
			"rally_cry",
			"siege_slam",
			"feral_instinct",
			"berserker_mode",
		},
		GoldReward = { Chance = 1.00, MinQty = 150, MaxQty = 300 },
		DropTable  = {
			{ ItemId = "evolution_shard",       Chance = 0.60, MinQty = 1, MaxQty = 1 },
			{ ItemId = "rare_collectible",      Chance = 0.40, MinQty = 1, MaxQty = 1 },
			{ ItemId = "evolution_crystal",     Chance = 0.20, MinQty = 1, MaxQty = 1 },
			{ ItemId = "orc_warbrand_frag",     Chance = 0.15, MinQty = 1, MaxQty = 1 },
			{ ItemId = "legend_trap",           Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large",       Chance = 0.10, MinQty = 1, MaxQty = 1 },
			{ ItemId = "stamina_potion",        Chance = 0.10, MinQty = 2, MaxQty = 2 },
		},
		SilverReward = 50,
		ExpReward    = 100,
		ModelId      = "orc_overlord",
	},

	-- ==========================================================================
	-- ABYSS RIFT  (dungeon_abyss) — entry Lv 601, step 80, boss Lv 1000 (capped)
	-- ==========================================================================

	demon = {
		Name      = "Demon",
		Element   = "dark",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_abyss",
		BaseStats = { HP = 14, ATK = 5, DEF = 1, SPD = 4 },
		ImmuneTo  = {},
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "shadow_claw", "dark_pulse", "soul_rend", "void_step" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "demon_shard",    Chance = 0.08, MinQty = 1, MaxQty = 1 },
			{ ItemId = "void_crystal",   Chance = 0.03, MinQty = 1, MaxQty = 1 },
			{ ItemId = "abyss_essence",  Chance = 0.01, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large", Chance = 0.04, MinQty = 1, MaxQty = 1 },
			{ ItemId = "legend_trap",    Chance = 0.01, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 20,
		ModelId      = "demon",
	},

	specter = {
		Name      = "Specter",
		Element   = "dark",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_abyss",
		BaseStats = { HP = 12, ATK = 4, DEF = 0.5, SPD = 3.5 },
		ImmuneTo  = { "Poison", "Bleed" },
		ElementalVulnerability = {},
		AIBehavior  = "aggressive",
		AbilityPool = { "soul_touch", "haunting_gaze", "wailing_scream", "ethereal_form" },
		GoldReward  = { Chance = 0.02, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "specter_essence", Chance = 0.08, MinQty = 1, MaxQty = 1 },
			{ ItemId = "void_shard",      Chance = 0.04, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large", Chance = 0.03, MinQty = 1, MaxQty = 1 },
			{ ItemId = "legend_trap",     Chance = 0.01, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 20,
		ModelId      = "specter",
	},

	dark_troll = {
		Name      = "Dark Troll",
		Element   = "dark",
		IsBoss    = false,
		PhaseCount = 1,
		Capturable = false,
		Dungeon   = "dungeon_abyss",
		BaseStats = { HP = 28, ATK = 5, DEF = 2, SPD = 1.5 },
		ImmuneTo  = {},
		ElementalVulnerability = { light = 1.50 },
		AIBehavior  = "defensive",
		AbilityPool = { "shadow_bash", "void_smash", "shadow_cleave", "abyssal_roar", "dark_regeneration" },
		GoldReward  = { Chance = 0.04, Multiplier = 0.1, MinQty = 1 },
		DropTable   = {
			{ ItemId = "dark_troll_hide", Chance = 0.06, MinQty = 1, MaxQty = 1 },
			{ ItemId = "abyssal_stone",   Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "abyss_essence",   Chance = 0.01, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large", Chance = 0.04, MinQty = 1, MaxQty = 1 },
			{ ItemId = "legend_trap",     Chance = 0.01, MinQty = 1, MaxQty = 1 },
		},
		SilverReward = 5,
		ExpReward    = 30,
		ModelId      = "dark_troll",
	},

	boss_abyssal_demon_lord = {
		Name      = "Abyssal Demon Lord",
		Element   = "dark",
		IsBoss    = true,
		PhaseCount = 3,
		Capturable = false,
		Dungeon   = "dungeon_abyss",
		BaseStats = { HP = 65, ATK = 6, DEF = 2, SPD = 2.5 },
		ImmuneTo  = { "Bind" },
		ElementalVulnerability = {},
		PhaseThresholds     = { [2] = 0.60, [3] = 0.30 },
		PhaseStatMultipliers = {
			[1] = {},
			[2] = { ATK = 0.20 },  -- Chaos Form: +20% ATK permanently; all attacks gain Dark typing (behavioral)
			[3] = {},               -- Soul Absorption: passive regen (behavioral, not a stat delta)
		},
		AIBehavior  = "aggressive",
		AbilityPool = {
			"abyssal_strike",
			"abyssal_slash",
			"void_rupture",
			"dark_assimilation",
			"chaos_form",
			"infernal_throne",
			"soul_absorption",
			"eternal_darkness",
		},
		GoldReward = { Chance = 1.00, MinQty = 400, MaxQty = 800 },
		DropTable  = {
			{ ItemId = "evolution_shard",   Chance = 0.60, MinQty = 1, MaxQty = 1 },
			{ ItemId = "rare_collectible",  Chance = 0.40, MinQty = 1, MaxQty = 1 },
			{ ItemId = "evolution_crystal", Chance = 0.20, MinQty = 1, MaxQty = 1 },
			{ ItemId = "abyss_essence",     Chance = 0.15, MinQty = 1, MaxQty = 1 },
			{ ItemId = "legend_trap",       Chance = 0.05, MinQty = 1, MaxQty = 1 },
			{ ItemId = "hp_potion_large",   Chance = 0.10, MinQty = 1, MaxQty = 1 },
			{ ItemId = "stamina_potion",    Chance = 0.10, MinQty = 2, MaxQty = 2 },
		},
		SilverReward = 50,
		ExpReward    = 100,
		ModelId      = "abyssal_demon_lord",
	},
}
